//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DataAccess
{
	private UserEvent UserEvents
	{
		get;
		set;
	}

	public virtual void putEvent()
	{
		throw new System.NotImplementedException();
	}

	public virtual UserEvent getEvents()
	{
		throw new System.NotImplementedException();
	}

	public virtual void removeEvent()
	{
		throw new System.NotImplementedException();
	}

}

