//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

public class Program
{
	public static void Main(string[] args)
	{
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);

        var form = new MainForm();
        try
        {
            using (NotifyIcon icon = new NotifyIcon())
            {
                icon.Icon = Icon.ExtractAssociatedIcon(Application.ExecutablePath);
                icon.ContextMenu = new ContextMenu(
                    new[] 
                { 
                    new MenuItem("Show", (s, e) => form.Show()),
                    new MenuItem("Hide", (s, e) => form.Hide()),
                    new MenuItem("Exit", (s, e) => Application.Exit())
                }
                );
                icon.Visible = true;

                Application.Run(form);
                icon.Visible = false;
            }
        }
        catch(System.ObjectDisposedException ex)
        {

        }

        //Application.Run(new MainForm());
	}
}

