//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UserEvent
{
	private string text;
    private string dateTime;
	private int level;

    public UserEvent(string text, string dateTime, int level)
    {
        this.text = text;
        this.dateTime = dateTime;
        this.level = level;
    }

    public string GetText()
    {
        return this.text;
    }
    public string GetDateAndTime()
    {
        return this.dateTime;
    }

    public int GetLevel()
    {
        return this.level;
    }

    public string ToString()
    {
        string s = this.dateTime + "|" + this.text + "|" + this.level.ToString();
        return s;
    }
}

